;;; ar-ert-execute-block-test.el --- ar-execute-block tests

;; URL: https://github.com/andreas-roehler/emacs-generics
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(ert-deftest ar-ert-execute-block-SomeMode-test ()
  (let ((buffer (ar--choose-buffer-name "SomeMode")))
    (ar-test
        "if True:
    print(\"one\")
    print(\"two\")"
      (ar-execute-block-SomeMode)
      (set-buffer buffer)
      (should (search-backward "two")))))

(ert-deftest ar-ert-execute-block-SomeMode2-test ()
  (let ((buffer (ar--choose-buffer-name "SomeMode2")))
    (ar-test
        "if True:
    print(\"one\")
    print(\"two\")"
      (ar-execute-block-SomeMode2)
      (set-buffer buffer)
      (should (search-backward "two")))))

(ert-deftest ar-ert-execute-block-SomeMode3-test ()
  (let ((buffer (ar--choose-buffer-name "SomeMode3")))
    (ar-test
        "if True:
    print(\"one\")
    print(\"two\")"
      (ar-execute-block-SomeMode3)
      (set-buffer buffer)
      (should (search-backward "two")))))

(ert-deftest ar-ert-execute-block-iSomeMode-test ()
  (let ((buffer (ar--choose-buffer-name "iSomeMode")))
    (ar-test
        "if True:
    print(\"one\")
    print(\"two\")"
      (ar-execute-block-iSomeMode)
      (set-buffer buffer)
      (should (search-backward "two")))))

(ert-deftest ar-ert-execute-block-iSomeMode3-test ()
  (let ((buffer (ar--choose-buffer-name "iSomeMode3")))
    (ar-test
        "if True:
    print(\"one\")
    print(\"two\")"
      (ar-execute-block-iSomeMode3)
      (set-buffer buffer)
      (should (search-backward "two")))))

(provide 'ar-ert-execute-block-test)
;;; ar-ert-execute-block-test.el here
