;;; ar-ert-always-split-tests.el --- Test splitting -*- lexical-binding: t; -*-

;; URL: https://github.com/andreas-roehler/emacs-generics
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(require 'ar-setup-ert-tests)

(ert-deftest ar-ert-always-split-dedicated-lp-1361531-SomeMode-test ()
  (ar-test
      "#! /usr/bin/env SomeMode
# -*- coding: utf-8 -*-
print(\"I'm the ar-always-split-dedicated-lp-1361531-SomeMode-test\")"
    (delete-other-windows)
    (let* ((ar-split-window-on-execute 'always)
	   (erg1 (progn (ar-execute-statement-SomeMode-dedicated) ar-output-buffer))
	   (erg2 (progn (ar-execute-statement-SomeMode-dedicated) ar-output-buffer)))
      (sit-for 0.1 t)
      (when ar-debug-p (message "(count-windows) %s" (count-windows)))
      (should (< 2 (count-windows)))
      (ar-kill-buffer-unconditional erg1)
      (ar-kill-buffer-unconditional erg2)
      (ar-restore-window-configuration))))

(ert-deftest ar-ert-always-split-dedicated-lp-1361531-iSomeMode-test ()
  (ar-test
      "#! /usr/bin/env iSomeMode
# -*- coding: utf-8 -*-
print(\"I'm the ar-always-split-dedicated-lp-1361531-iSomeMode-test\")"
    (delete-other-windows)
    (let* ((ar-split-window-on-execute 'always)
	   (erg1 (progn (ar-execute-statement-iSomeMode-dedicated) ar-output-buffer))
	   (erg2 (progn (ar-execute-statement-iSomeMode-dedicated) ar-output-buffer)))
      (sit-for 0.1 t)
      (when ar-debug-p (message "(count-windows) %s" (count-windows)))
      (should (< 2 (count-windows)))
      (ar-kill-buffer-unconditional erg1)
      (ar-kill-buffer-unconditional erg2)
      (ar-restore-window-configuration))))

(ert-deftest ar-ert-always-split-dedicated-lp-1361531-jython-test ()
  (ar-test
      "#! /usr/bin/env jython
# -*- coding: utf-8 -*-
print(\"I'm the ar-always-split-dedicated-lp-1361531-jython-test\")"
    (delete-other-windows)
    (let* ((ar-split-window-on-execute 'always)
	   (erg1 (progn (ar-execute-statement-jython-dedicated) ar-output-buffer))
	   (erg2 (progn (ar-execute-statement-jython-dedicated) ar-output-buffer)))
      (sit-for 0.1 t)
      (when ar-debug-p (message "(count-windows) %s" (count-windows)))
      (should (< 2 (count-windows)))
      (ar-kill-buffer-unconditional erg1)
      (ar-kill-buffer-unconditional erg2)
      (ar-restore-window-configuration))))

(ert-deftest ar-ert-always-split-dedicated-lp-1361531-SomeMode3-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
print(\"I'm the ar-always-split-dedicated-lp-1361531-SomeMode3-test\")"
    (delete-other-windows)
    (let* ((ar-split-window-on-execute 'always)
	   (erg1 (progn (ar-execute-statement-SomeMode3-dedicated) ar-output-buffer))
	   (erg2 (progn (ar-execute-statement-SomeMode3-dedicated) ar-output-buffer)))
      (sit-for 0.1 t)
      (when ar-debug-p (message "(count-windows) %s" (count-windows)))
      (should (< 2 (count-windows)))
      (ar-kill-buffer-unconditional erg1)
      (ar-kill-buffer-unconditional erg2)
      (ar-restore-window-configuration))))

;; ar-ert-always-split-tests.el ends here
(provide 'ar-ert-always-split-tests)
