;;; ar-ert-forward-tests.el --- Just some more tests -*- lexical-binding: t; -*-

;; URL: https://github.com/andreas-roehler/emacs-generics
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:


;;This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

(require 'ar-setup-ert-tests)

(ert-deftest ar-ert-forward-block-test ()
  (ar-test-point-min
   "if foo:
    for a in b:
        print('%(language)s has %(number)03d quote types.' %
   {'language': \"SOME\", \"number\": 2})
elif bar:
    for a in b:
        pass
else:
    for a in b:
        pass
"
   'SomeMode-mode
   'ar-verbose-p
   (goto-char (point-min))
   (let (ar-font-lock-defaults-p)
     (ar-forward-block)
     (should (eobp)))))

(ert-deftest ar-ert-forward-block-or-clause-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "elif")
   (ar-forward-block-or-clause)
   (should (eq (char-before) ?s))))

(ert-deftest ar-ert-forward-class-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \\\"SOME\\\", \\\"number\\\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-class)
   (should (eq (char-before) ?2))))

(ert-deftest ar-ert-forward-clause-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "elif")
   (ar-forward-clause)
   (should (eq (char-before) ?s))))

(ert-deftest ar-ert-forward-def-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-def)
   (should (eq (char-before) ?2))))

(ert-deftest ar-ert-forward-def-or-class-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-def-or-class)
   (should (eq (char-before) ?2))))

(ert-deftest ar-ert-forward-elif-block-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "elif")
   (ar-forward-elif-block)
   (should (eq (char-before) ?s))))

(ert-deftest ar-ert-forward-else-block-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "else")
   (ar-forward-else-block)
   (should (eq (char-before) ?s))))

(ert-deftest ar-ert-forward-except-block-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "except")
   (ar-forward-except-block)
   (should (eq (char-before) ?2))))

(ert-deftest ar-ert-forward-expression-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-expression)
   (should (eq (char-before) ?:))))

(ert-deftest ar-ert-forward-for-block-test ()
  (ar-test
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (goto-char (point-max)) 
   (search-backward "for")
   (ar-forward-for-block)
   (should (looking-back "pass" (line-beginning-position)))))

(ert-deftest ar-ert-forward-if-block-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-if-block)
   (should (eq (char-before) ?s))))

(ert-deftest ar-ert-forward-minor-block-test-0nXANF ()
  (ar-test
      "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char (point-min))
    (search-forward "if")
    (ar-forward-minor-block)
    (should (eq (char-before) ?s))))

(ert-deftest ar-ert-forward-minor-block-test-JNJyc4 ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (goto-char (point-min))
   (search-forward "try:")
   (ar-forward-minor-block)
   (should (eq (char-before) ?2))))

(ert-deftest ar-ert-forward-partial-expression-test ()
  (ar-test
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (goto-char (point-max))
   (search-backward "Pyt")
   (ar-forward-partial-expression)
   (should (eq (char-before) ?n))))

(ert-deftest ar-ert-forward-section-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-section)
   (should (eq (char-before) ?}))))

(ert-deftest ar-ert-forward-statement-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-statement)
   (should (eq (char-before) ?:))))

(ert-deftest ar-ert-forward-top-level-test ()
  (ar-test-point-min
   "# {{
class bar:
    def foo ():
        try:
            if foo:
                for a in b:
                    print('%(language)s has %(number)03d quote types.' %
       {'language': \"SOME\", \"number\": 2})
            elif bar:
                for a in b:
                    pass
            else:
                for a in b:
                    pass
# }}
        except:
            block2
"
   'SomeMode-mode
   'ar-verbose-p
   (search-forward "if")
   (ar-forward-top-level)
   (should (eq (char-before) ?2))))

(ert-deftest ar-ert-forward-try-block-test ()
  (ar-test
      "
def foo():
    if True:
        def bar():
            pass
    elif False:
        def baz():
            pass
    else:
        try:
            1 == 1
        except True:
            def foo1():
                if True:
                    def bar1():
                        pass
                elif False:
                    def baz1():
                        pass
                else:
                    try:
                        1 == 1
                    except True:
                        pass
                    else True:
                        pass
                    finally:
                        print(\"asdf\")
        else True:
            pass
        finally:
            pass
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char (point-min))
    (search-forward "try")
    (ar-forward-try-block)
    (should (looking-back "pass" (line-beginning-position)))))

(ert-deftest ar-ert-forward-block-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-block-bol)
    (should (looking-at " +except:"))))

(ert-deftest ar-ert-forward-clause-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-clause-bol)
    (should (bolp))))

(ert-deftest ar-ert-forward-block-or-clause-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-block-or-clause-bol)
    (should (looking-at " +except:"))))

(ert-deftest ar-ert-forward-def-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-def-bol)
    (should (eobp))))

(ert-deftest ar-ert-forward-class-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-class-bol)
    (should (eobp))))

(ert-deftest ar-ert-forward-def-or-class-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-def-or-class-bol)
    (should (eobp))))

(ert-deftest ar-ert-forward-if-block-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-if-block-bol)
    (should (looking-at " +except:"))))

(ert-deftest ar-ert-forward-try-block-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-try-block-bol)
    (should (eobp))))

(ert-deftest ar-ert-forward-minor-block-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-minor-block-bol)
    (should (looking-at " +except:"))))


(ert-deftest ar-ert-forward-for-block-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-for-block-bol)
    (should (looking-at " +except:"))))

(ert-deftest ar-ert-forward-top-level-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-top-level-bol)
    (should (eobp))))

(ert-deftest ar-ert-forward-statement-bol-test ()
  (ar-test
      "# -*- coding: utf-8 -*-
class bar:
    def foo ():
        try:
            if True:
                for a in b:
                    pass
"
    'SomeMode-mode
    'ar-verbose-p
    (goto-char 103)
    (ar-forward-statement-bol)
    (should (looking-at " +pass"))))

(ert-deftest ar-ert-forward-statement-test-7MuP64 ()
  (ar-test-point-min
   "def wwwwww_wwwwwww(self, text):
		# wwwwww www wwww wwww wwwwwww, w.w. <!-- wwwwww wwwwwwwwww wwww wwww -->
		# wwwwwwwwwww www wwwwwwww wwwwwww.
		self.wwwwww.append(\"<!--%(text)s-->\" % locals())"
   'SomeMode-mode
   'ar-verbose-p
   (end-of-line)
   (ar-forward-statement)
   (should (eq (char-before) 41))))

(provide 'ar-ert-forward-tests)
;;; ar-ert-forward-tests.el ends here
