;;; ar-split-just-two-window-on-execute-test.el --- Test splitting

;; URL: https://github.com/andreas-roehler/emacs-generics
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(require 'ar-setup-ert-tests)

(defun ar-split-just-two-window-on-execute-lp-1361531-SomeMode-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute 'just-two)
        (teststring "#! /usr/bin/env SomeMode
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-just-two-window-on-execute-lp-1361531-SomeMode-test\")"))
    (ar-bug-tests-intern 'ar-split-just-two-window-on-execute-lp-1361531-SomeMode-base arg teststring)))

(defun ar-split-just-two-window-on-execute-lp-1361531-SomeMode-base (arg)
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (when ar-debug-p (switch-to-buffer (current-buffer))(font-lock-ensure))
  (let ((ar-split-window-on-execute 'just-two)
        (erg1 (progn (ar-execute-statement-SomeMode) ar-output-buffer))
        (erg2 (progn (ar-execute-statement-SomeMode3) ar-output-buffer)))
    (sit-for 0.1 t)
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-SomeMode (count-windows); %s" (count-windows)))
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-SomeMode (window-list): %s" (window-list)))
    (and
     (assert (eq 2 (count-windows)) nil "ar-split-just-two-window-on-execute-lp-1361531-SomeMode-test failed")
     (message "%s" "ar-split-just-two-window-on-execute-lp-1361531-SomeMode-test passed"))
    (ar-kill-buffer-unconditional erg1)
    (ar-kill-buffer-unconditional erg2)
    (ar-restore-window-configuration)))

(defun ar-split-just-two-window-on-execute-lp-1361531-iSomeMode-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute 'just-two)
        (teststring "#! /usr/bin/env iSomeMode
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-just-two-window-on-execute-lp-1361531-iSomeMode-test\")"))
    (ar-bug-tests-intern 'ar-split-just-two-window-on-execute-lp-1361531-iSomeMode-base arg teststring)))

(defun ar-split-just-two-window-on-execute-lp-1361531-iSomeMode-base (arg)
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (when ar-debug-p (switch-to-buffer (current-buffer))(font-lock-ensure))
  (let ((ar-split-window-on-execute 'just-two)
        (erg1 (progn (ar-execute-statement-iSomeMode) ar-output-buffer))
        (erg2 (progn (ar-execute-statement-jython) ar-output-buffer)))
    (sit-for 0.1 t)
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-iSomeMode (count-windows); %s" (count-windows)))
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-iSomeMode (window-list): %s" (window-list)))
    (and
     (assert (eq 2 (count-windows)) nil "ar-split-just-two-window-on-execute-lp-1361531-iSomeMode-test failed")
     (message "%s" "ar-split-just-two-window-on-execute-lp-1361531-iSomeMode-test passed"))
    (ar-kill-buffer-unconditional erg1)
    (ar-kill-buffer-unconditional erg2)
    (ar-restore-window-configuration)))

(defun ar-split-just-two-window-on-execute-lp-1361531-SomeMode2-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute 'just-two)
        (teststring "#! /usr/bin/env SomeMode2
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-just-two-window-on-execute-lp-1361531-SomeMode2-test\")"))
    (ar-bug-tests-intern 'ar-split-just-two-window-on-execute-lp-1361531-SomeMode2-base arg teststring)))

(defun ar-split-just-two-window-on-execute-lp-1361531-SomeMode2-base (arg)
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (when ar-debug-p (switch-to-buffer (current-buffer))(font-lock-ensure))
  (let ((ar-split-window-on-execute 'just-two)
        (erg1 (progn (ar-execute-statement-SomeMode2) ar-output-buffer))
        (erg2 (progn (ar-execute-statement-SomeMode2) ar-output-buffer)))
    (sit-for 0.1 t)
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-SomeMode2 (count-windows); %s" (count-windows)))
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-SomeMode2 (window-list): %s" (window-list)))
    (and
     (assert (eq 2 (count-windows)) nil "ar-split-just-two-window-on-execute-lp-1361531-SomeMode2-test failed")
     (message "%s" "ar-split-just-two-window-on-execute-lp-1361531-SomeMode2-test passed"))
    (ar-kill-buffer-unconditional erg1)
    (ar-kill-buffer-unconditional erg2)
    (ar-restore-window-configuration)))

(defun ar-split-just-two-window-on-execute-lp-1361531-jython-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute 'just-two)
        (teststring "#! /usr/bin/env jython
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-just-two-window-on-execute-lp-1361531-jython-test\")"))
    (ar-bug-tests-intern 'ar-split-just-two-window-on-execute-lp-1361531-jython-base arg teststring)))

(defun ar-split-just-two-window-on-execute-lp-1361531-jython-base (arg)
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (when ar-debug-p (switch-to-buffer (current-buffer))(jit-lock-fontify-now))
  (let ((ar-split-window-on-execute 'just-two)
        (erg1 (progn (ar-execute-statement-jython) ar-output-buffer))
        (erg2 (progn (ar-execute-statement-iSomeMode) ar-output-buffer)))
    (sit-for 0.1 t)
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-jython (count-windows); %s" (count-windows)))
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-jython (window-list): %s" (window-list)))
    (and
     (assert (eq 2 (count-windows)) nil "ar-split-just-two-window-on-execute-lp-1361531-jython-test failed")
     (message "%s" "ar-split-just-two-window-on-execute-lp-1361531-jython-test passed"))
    (ar-kill-buffer-unconditional erg1)
    (ar-kill-buffer-unconditional erg2)
    (ar-restore-window-configuration)))

(defun ar-split-just-two-window-on-execute-lp-1361531-SomeMode3-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute 'just-two)
        (teststring "# -*- coding: utf-8 -*-
print(\"I'm the ar-split-just-two-window-on-execute-lp-1361531-SomeMode3-test\")"))
    (ar-bug-tests-intern 'ar-split-just-two-window-on-execute-lp-1361531-SomeMode3-base arg teststring)))

(defun ar-split-just-two-window-on-execute-lp-1361531-SomeMode3-base (arg)
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (when ar-debug-p (switch-to-buffer (current-buffer))(jit-lock-fontify-now))
  (let ((ar-split-window-on-execute 'just-two)
        (erg1 (progn (ar-execute-statement-SomeMode3) ar-output-buffer))
        (erg2 (progn (ar-execute-statement-SomeMode) ar-output-buffer)))
    (sit-for 0.1 t)
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-SomeMode3 (count-windows); %s" (count-windows)))
    (when ar-debug-p (message "just-two-window-on-execute-lp-1361531-SomeMode3 (window-list): %s" (window-list)))
    (and
     (assert (eq 2 (count-windows)) nil "ar-split-just-two-window-on-execute-lp-1361531-SomeMode3-test failed")
     (message "%s" "ar-split-just-two-window-on-execute-lp-1361531-SomeMode3-test passed"))
    (ar-kill-buffer-unconditional erg1)
    (ar-kill-buffer-unconditional erg2)
    (ar-restore-window-configuration)))

(provide 'ar-split-just-two-window-on-execute-test)
;;; ar-split-just-two-window-on-execute-test.el here
