;;; ar-shell-arg-ert-tests.el --- ar-shell ert tests -*- lexical-binding: t; -*- 

;; URL: https://github.com/andreas-roehler/emacs-generics
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(ert-deftest ar-ert-SomeMode-shell-test ()
  (let ((ar-SomeMode-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*SOME*")
    (SomeMode)
    (should (buffer-live-p (get-buffer "*SOME*")))
    (set-buffer (get-buffer "*SOME*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(ert-deftest ar-ert-SomeMode2-shell-test ()
  (let ((ar-SomeMode2-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*SOME2*")
    (SomeMode2)
    (should (buffer-live-p (get-buffer "*SOME2*")))
    (set-buffer (get-buffer "*SOME2*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(ert-deftest ar-ert-SomeMode3-shell-test ()
  (let ((ar-SomeMode3-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*SOME3*")
    (SomeMode3)
    (should (buffer-live-p (get-buffer "*SOME3*")))
    (set-buffer (get-buffer "*SOME3*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(ert-deftest ar-ert-iSomeMode-shell-test ()
  (let ((ar-iSomeMode-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*ISOME*")
    (iSomeMode)
    (should (buffer-live-p (get-buffer "*ISOME*")))
    (set-buffer (get-buffer "*ISOME*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(ert-deftest ar-ert-iSomeMode2-shell-test ()
  (let ((ar-iSomeMode2-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*ISOME2*")
    (iSomeMode2)
    (should (buffer-live-p (get-buffer "*ISOME2*")))
    (set-buffer (get-buffer "*ISOME2*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(ert-deftest ar-ert-iSomeMode3-shell-test ()
  (let ((ar-iSomeMode3-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*ISOME3*")
    (iSomeMode3)
    (should (buffer-live-p (get-buffer "*ISOME3*")))
    (set-buffer (get-buffer "*ISOME3*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(ert-deftest ar-ert-jython-shell-test ()
  (let ((ar-jython-command-args  (list "-i -c\"abc=4\"")))
    (ar-kill-buffer-unconditional "*Jython*")
    (jython)
    (should (buffer-live-p (get-buffer "*Jython*")))
    (set-buffer (get-buffer "*Jython*"))
    (should (string= "4" ar-result))
    (should (< 1 comint-last-input-end))))

(provide 'ar-shell-arg-ert-tests)
;;; ar-shell-arg-ert-tests.el ends here
 
