;;; ar-split-window-on-execute-test.el --- Test splitting

;; URL: https://github.com/andreas-roehler/emacs-generics
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from SomeMode-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:


(defun ar-split-window-on-execute-lp-1361531-SomeMode-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute t)
        (teststring "#! /usr/bin/env SomeMode
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-window-on-execute-lp-1361531-SomeMode-test\")"))
    (ar-bug-tests-intern 'ar-split-window-on-execute-lp-1361531-SomeMode-base arg teststring)))

(defun ar-split-window-on-execute-lp-1361531-SomeMode-base ()
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (ar-execute-statement)
  (assert (eq 2 (count-windows)) nil "ar-split-window-on-execute-lp-1361531-SomeMode-test failed")
  (ar-kill-buffer-unconditional (current-buffer)))

(defun ar-split-window-on-execute-lp-1361531-iSomeMode-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute t)
        (teststring "#! /usr/bin/env iSomeMode
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-window-on-execute-lp-1361531-iSomeMode-test\")"))
    (ar-bug-tests-intern 'ar-split-window-on-execute-lp-1361531-iSomeMode-base arg teststring)))

(defun ar-split-window-on-execute-lp-1361531-iSomeMode-base ()
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (ar-execute-statement)
  (assert (eq 2 (count-windows)) nil "ar-split-window-on-execute-lp-1361531-iSomeMode-test failed")
  (ar-kill-buffer-unconditional (current-buffer)))

(defun ar-split-window-on-execute-lp-1361531-SomeMode2-test ()
  (interactive)
  (let ((ar-split-window-on-execute t)
        (teststring "#! /usr/bin/env SomeMode2
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-window-on-execute-lp-1361531-SomeMode2-test\")"))
    (ar-bug-tests-intern 'ar-split-window-on-execute-lp-1361531-SomeMode2-base)))

(defun ar-split-window-on-execute-lp-1361531-SomeMode2-base ()
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (ar-execute-statement)
  (assert (eq 2 (count-windows)) nil "ar-split-window-on-execute-lp-1361531-SomeMode2-test failed")
  (ar-kill-buffer-unconditional (current-buffer)))

(defun ar-split-window-on-execute-lp-1361531-jython-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute t)
        (teststring "#! /usr/bin/env jython
# -*- coding: utf-8 -*-
print(\"I'm the ar-split-window-on-execute-lp-1361531-jython-test\")"))
    (ar-bug-tests-intern 'ar-split-window-on-execute-lp-1361531-jython-base arg teststring)))

(defun ar-split-window-on-execute-lp-1361531-jython-base ()
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (ar-execute-statement)
  (assert (eq 2 (count-windows)) nil "ar-split-window-on-execute-lp-1361531-jython-test failed")
  (ar-kill-buffer-unconditional (current-buffer)))

(defun ar-split-window-on-execute-lp-1361531-SomeMode3-test (&optional arg)
  (interactive "p")
  (let ((ar-split-window-on-execute t)
        (teststring "# -*- coding: utf-8 -*-
print(\"I'm the ar-split-window-on-execute-lp-1361531-SomeMode3-test\")"))
    (ar-bug-tests-intern 'ar-split-window-on-execute-lp-1361531-SomeMode3-base arg teststring)))

(defun ar-split-window-on-execute-lp-1361531-SomeMode3-base ()
  (when ar-debug-p (message "ar-split-window-on-execute: %s" ar-split-window-on-execute))
  (delete-other-windows)
  (ar-execute-statement)
  (assert (eq 2 (count-windows)) nil "ar-split-window-on-execute-lp-1361531-SomeMode3-test failed")
  (ar-kill-buffer-unconditional (current-buffer)))

(provide 'ar-split-window-on-execute-test)
;;; ar-split-window-on-execute-test.el here
