;;; ar-mode.el --- Edit, debug, develop and run programs. -*- lexical-binding: t; -*-

;; used by ar-hungry-delete-backwards
(require (quote cc-cmds))
(require (quote ar-vars))
(require (quote ar-setup-ert-tests))
(require (quote ar-rx))
(require (quote ar-statement))
(require (quote ar-start1))
(require (quote ar-extra))
(require (quote ar-shift-forms))
(require (quote ar-down))
(require (quote ar-start-Zf98zM))
(require (quote ar-backward-forms))
(require (quote ar-forward-forms))
(require (quote ar-start2))
(require (quote ar-start3))
(require (quote ar-execute-file))
(require (quote ar-up))
(require (quote ar-booleans-beginning-forms))
(require (quote ar-move))
(require (quote ar-end-position-forms))
(require (quote ar-beginning-position-forms))
(require (quote ar-extended-executes))
(require (quote ar-execute))
(require (quote ar-compute-indentation))
(require (quote ar-intern))
(require (quote ar-copy-forms))
(require (quote ar-delete-forms))
(require (quote ar-mark-forms))
(require (quote ar-copy-forms))
(require (quote ar-delete-forms))
(require (quote ar-close-forms))
(require (quote ar-kill-forms))
(require (quote ar-forms-code))
(require (quote ar-booleans-end-forms))
(require (quote ar-exec-forms))
(require (quote ar-switches))
(require (quote ar-edit))
(require (quote ar-named-shells))
(require (quote ar-font-lock))
(require (quote ar-menu))
(require (quote ar-map))
(require (quote ar-shell-menu))
(require (quote ar-complete))
(require (quote ar-pdb))
(require (quote ar-pdbtrack))
(require (quote ar-help))
(require (quote ar-extensions))
(require (quote ar-imenu))
;; now installed by ar-load-named-shells
;; (require (quote ar-named-shells))
(require (quote ar-electric))
(require (quote ar-virtualenv))
(require (quote ar-abbrev-propose))
(require (quote ar-paragraph))
(require (quote ar-section-forms))
(require (quote ar-comment))
(require (quote ar-fast-forms))
(require (quote ar-narrow))
(require (quote ar-hide-show))
(require (quote ar-ffap))
(require (quote ar-foot))

(provide 'ar-mode) ;; generic mark 
;;; ar-mode.el ends her
